"""initial tables

Revision ID: f871c4025951
Revises: 
Create Date: 2026-08-29 19:16:11.272315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f871c4025951'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_category'), ['category'], unique=False)

    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklist_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_blacklist_issue_type'), ['issue_type'], unique=False)

    op.create_table('job_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_category'), ['category'], unique=False)

    op.create_table('offer_weight_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dimension_key', sa.String(length=50), nullable=False),
    sa.Column('dimension_name', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dimension_key')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_review_status'), ['review_status'], unique=False)

    op.create_table('scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_done'), ['done'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type_id', sa.Integer(), nullable=True),
    sa.Column('version_name', sa.String(length=100), nullable=False),
    sa.Column('target_position', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_job_type_id'), ['job_type_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('apply_time', sa.DateTime(), nullable=True),
    sa.Column('resume_version_id', sa.Integer(), nullable=True),
    sa.Column('job_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_apply_time'), ['apply_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_job_type_id'), ['job_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('resume_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resume_version_id', sa.Integer(), nullable=False),
    sa.Column('change_desc', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('trigger_source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_logs_resume_version_id'), ['resume_version_id'], unique=False)

    op.create_table('application_status_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_status_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_status_logs_application_id'), ['application_id'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('exam_time', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('exam_link', sa.String(length=500), nullable=True),
    sa.Column('account', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_application_id'), ['application_id'], unique=False)

    op.create_table('interviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.String(length=20), nullable=True),
    sa.Column('interview_time', sa.DateTime(), nullable=True),
    sa.Column('interview_link', sa.String(length=500), nullable=True),
    sa.Column('self_intro', sa.Text(), nullable=True),
    sa.Column('prep_checklist', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_application_id'), ['application_id'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('salary_base', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_months', sa.Integer(), nullable=True),
    sa.Column('bonus_performance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('signing_bonus', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('housing_fund', sa.String(length=100), nullable=True),
    sa.Column('stock_options', sa.String(length=200), nullable=True),
    sa.Column('work_intensity', sa.Integer(), nullable=True),
    sa.Column('industry_prospect', sa.Integer(), nullable=True),
    sa.Column('company_scale', sa.String(length=100), nullable=True),
    sa.Column('position_development', sa.Integer(), nullable=True),
    sa.Column('other_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extra_scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_company'), ['company'], unique=False)

    op.create_table('exam_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.String(length=100), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('wrong_questions', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', name='uq_exam_review_exam_id')
    )
    with op.batch_alter_table('exam_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_reviews_exam_id'), ['exam_id'], unique=False)

    op.create_table('interview_qa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('my_answer', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_qa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_qa_interview_id'), ['interview_id'], unique=False)

    op.create_table('interview_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('fail_reason', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', name='uq_interview_result_interview_id')
    )
    with op.batch_alter_table('interview_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_results_interview_id'), ['interview_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_results_interview_id'))

    op.drop_table('interview_results')
    with op.batch_alter_table('interview_qa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_qa_interview_id'))

    op.drop_table('interview_qa')
    with op.batch_alter_table('exam_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_reviews_exam_id'))

    op.drop_table('exam_reviews')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_company'))
        batch_op.drop_index(batch_op.f('ix_offers_application_id'))

    op.drop_table('offers')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_application_id'))

    op.drop_table('interviews')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_application_id'))

    op.drop_table('exams')
    with op.batch_alter_table('application_status_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_status_logs_application_id'))

    op.drop_table('application_status_logs')
    with op.batch_alter_table('resume_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_logs_resume_version_id'))

    op.drop_table('resume_logs')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_job_type_id'))
        batch_op.drop_index(batch_op.f('ix_applications_company'))
        batch_op.drop_index(batch_op.f('ix_applications_apply_time'))

    op.drop_table('applications')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_job_type_id'))

    op.drop_table('resumes')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_done'))

    op.drop_table('tasks')
    op.drop_table('settings')
    op.drop_table('scripts')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_review_status'))
        batch_op.drop_index(batch_op.f('ix_questions_category'))

    op.drop_table('questions')
    op.drop_table('offer_weight_config')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_category'))

    op.drop_table('materials')
    op.drop_table('job_types')
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklist_issue_type'))
        batch_op.drop_index(batch_op.f('ix_blacklist_company'))

    op.drop_table('blacklist')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_category'))

    op.drop_table('assets')
    # ### end Alembic commands ###